"""
Environment Setup
=================
Sets up a UV-managed Python environment with pytest, Playwright, and Allure
for the generated test project. Runs in a background QThread so the IDE stays responsive.

Usage (called automatically from main_window.py after code generation):
    worker = EnvSetupWorker(project_dir)
    worker.log.connect(console_text.append)
    worker.finished.connect(on_done)
    worker.start()
"""

import os
import subprocess
import sys

from PyQt6.QtCore import QThread, pyqtSignal


# ──────────────────────────────────────────────────────────────────────────────
# Templates
# ──────────────────────────────────────────────────────────────────────────────

PYPROJECT_TEMPLATE = """\
[project]
name = "auto-tests"
version = "0.1.0"
description = "Automated tests generated by SikuliPy Web Inspector"
requires-python = ">=3.10"
dependencies = [
    "pytest>=7.0",
    "pytest-playwright>=0.4",
    "allure-pytest>=2.13",
    "opencv-python>=4.0",
    "pytesseract>=0.3",
    "numpy>=1.24",
]
"""

PYTEST_INI_CONTENT = """\
[pytest]
addopts = --alluredir=allure-results
"""


# ──────────────────────────────────────────────────────────────────────────────
# Setup logic
# ──────────────────────────────────────────────────────────────────────────────

def _run(cmd: list, cwd: str, log_fn):
    """Run a subprocess command and stream output to log_fn."""
    log_fn(f"[Env] > {' '.join(cmd)}")
    try:
        proc = subprocess.Popen(
            cmd,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        for line in proc.stdout:
            stripped = line.rstrip()
            if stripped:
                log_fn(f"[Env]   {stripped}")
        proc.wait()
        if proc.returncode != 0:
            log_fn(f"[Env] Warning: command exited with code {proc.returncode}")
        return proc.returncode
    except FileNotFoundError as exc:
        log_fn(f"[Env] Error: {exc}")
        return -1


def setup_project_environment(project_dir: str, log_fn) -> bool:
    """
    Ensure the test project has:
      - pyproject.toml  (created if absent)
      - pytest.ini      (created/overwritten)
      - UV virtual environment with all deps installed
      - Playwright browsers installed

    Returns True on success.
    """
    # 1. pyproject.toml — create only if missing
    pyproject_path = os.path.join(project_dir, "pyproject.toml")
    if not os.path.exists(pyproject_path):
        log_fn("[Env] Creating pyproject.toml …")
        with open(pyproject_path, "w", encoding="utf-8") as f:
            f.write(PYPROJECT_TEMPLATE)
    else:
        log_fn("[Env] pyproject.toml already exists — skipping creation.")

    # 2. pytest.ini — always write to keep it in sync
    pytest_ini = os.path.join(project_dir, "pytest.ini")
    log_fn("[Env] Writing pytest.ini …")
    with open(pytest_ini, "w", encoding="utf-8") as f:
        f.write(PYTEST_INI_CONTENT)

    # 3. Resolve the `uv` executable
    uv_cmd = _find_uv()
    if not uv_cmd:
        log_fn("[Env] Error: 'uv' not found on PATH. Install it from https://docs.astral.sh/uv/")
        return False

    # 4. uv sync — creates .venv and installs all deps declared in pyproject.toml
    log_fn("[Env] Installing dependencies with UV …")
    rc = _run([uv_cmd, "sync"], cwd=project_dir, log_fn=log_fn)
    if rc != 0:
        log_fn("[Env] Warning: 'uv sync' reported errors; continuing anyway.")

    # 5. Install Playwright browsers
    log_fn("[Env] Installing Playwright browsers …")
    rc = _run(
        [uv_cmd, "run", "playwright", "install", "--with-deps", "chromium"],
        cwd=project_dir,
        log_fn=log_fn,
    )
    if rc != 0:
        log_fn("[Env] Warning: Playwright browser install reported errors.")

    log_fn("[Env] Environment setup complete.")
    log_fn(f"[Env] Run tests: cd \"{project_dir}\" && uv run pytest -v")
    return True


def _find_uv() -> str | None:
    """Return the path to the uv executable, or None if not found."""
    import shutil
    # Check PATH first
    found = shutil.which("uv")
    if found:
        return found
    # Common Windows install location (Astral installer)
    candidates = [
        os.path.expanduser(r"~\.cargo\bin\uv.exe"),
        os.path.expanduser(r"~\.local\bin\uv"),
        r"C:\Program Files\uv\uv.exe",
    ]
    for c in candidates:
        if os.path.isfile(c):
            return c
    return None


# ──────────────────────────────────────────────────────────────────────────────
# Qt Worker thread
# ──────────────────────────────────────────────────────────────────────────────

class EnvSetupWorker(QThread):
    log = pyqtSignal(str)
    finished = pyqtSignal(bool)   # True = success

    def __init__(self, project_dir: str, parent=None):
        super().__init__(parent)
        self.project_dir = project_dir

    def run(self):
        ok = setup_project_environment(self.project_dir, self.log.emit)
        self.finished.emit(ok)
