"""
POM Generator
=============
Generates Page Object class files from Web Inspector captured element data.

Usage:
    from sikulipy.codegen.pom_generator import generate_page_object

    generate_page_object(
        project_dir="/path/to/project",
        page_name="home",
        url="https://example.com",
        elements=[
            {"id": "Buttons_0", "category": "Buttons", "text": "Submit", "ariaLabel": ""},
            ...
        ]
    )
"""

import os
import re


def _safe_name(text: str, fallback: str) -> str:
    """Convert display text into a valid Python identifier."""
    name = re.sub(r'[^a-zA-Z0-9]+', '_', text).strip('_').lower()
    return name if name else fallback.lower().replace(' ', '_')


def _class_name(page_name: str) -> str:
    return ''.join(word.capitalize() for word in re.split(r'[^a-zA-Z0-9]', page_name) if word) + 'Page'


def generate_page_object(project_dir: str, page_name: str, url: str, elements: list) -> str:
    """
    Generate a Page Object class file.

    Returns the absolute path to the written file.
    """
    pages_dir = os.path.join(project_dir, "pages")
    os.makedirs(pages_dir, exist_ok=True)

    # Create pages/__init__.py if absent
    init_path = os.path.join(pages_dir, "__init__.py")
    if not os.path.exists(init_path):
        open(init_path, 'w').close()

    cls = _class_name(page_name)
    lines = [
        f'"""',
        f'Page Object: {cls}',
        f'Generated by SikuliPy Web Inspector',
        f'URL: {url}',
        f'',
        f'TBD_ prefixes mark values that require manual completion.',
        f'"""',
        f'',
        f'from playwright.sync_api import Page',
        f'from sikulipy_testing import ImageAssertion, TextAssertion',
        f'',
        f'',
        f'class {cls}:',
        f'    def __init__(self, page: Page):',
        f'        self.page = page',
        f'',
        f'    def navigate(self):',
        f'        self.page.goto("{url}")',
        f'',
    ]

    # Group elements by category for readable output
    from collections import defaultdict
    by_category = defaultdict(list)
    name_counts = {}  # track duplicate method names

    for el in elements:
        by_category[el['category']].append(el)

    for category, els in by_category.items():
        lines.append(f'    # --- {category} ---')
        for i, el in enumerate(els):
            display = el['text'] if el['text'] else el.get('ariaLabel', '')
            fallback = f"{el['category'].lower()}_{i}"
            name = _safe_name(display, fallback)

            # Deduplicate method names within the class
            if name in name_counts:
                name_counts[name] += 1
                name = f"{name}_{name_counts[name]}"
            else:
                name_counts[name] = 0

            asset = el.get('_asset_path', f"TBD_ASSET_PATH_{name}")

            # click method
            lines += [
                f'',
                f'    def click_{name}(self):',
                f'        # TODO: fill in the CSS/XPath selector',
                f'        self.page.click("TBD_SELECTOR_{name}")',
                f'        # Alternatively, use image-based click (uncomment below):',
                f'        # ImageAssertion.click(self.page, "{asset}")',
            ]

            # assert visible method
            lines += [
                f'',
                f'    def assert_{name}_visible(self):',
                f'        ImageAssertion.assert_present(self.page, "{asset}")',
            ]

            # assert text method — only if element has a text label
            if display:
                lines += [
                    f'',
                    f'    def assert_{name}_text(self):',
                    f'        TextAssertion.assert_text(',
                    f'            self.page,',
                    f'            "{asset}",',
                    f'            expected="TBD_EXPECTED_{name.upper()}"',
                    f'        )',
                ]

        lines.append('')

    content = '\n'.join(lines)
    out_path = os.path.join(pages_dir, f"{page_name}_page.py")
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return out_path
