"""
Test Generator
==============
Generates a pytest test file from the list of elements captured by the Web Inspector,
paired with the corresponding Page Object class.

Usage:
    from sikulipy.codegen.test_generator import generate_test_file

    generate_test_file(
        project_dir="/path/to/project",
        page_name="home",
        url="https://example.com",
        elements=[...]
    )
"""

import os
import re


def _class_name(page_name: str) -> str:
    return ''.join(word.capitalize() for word in re.split(r'[^a-zA-Z0-9]', page_name) if word) + 'Page'


def _safe_name(text: str, fallback: str) -> str:
    name = re.sub(r'[^a-zA-Z0-9]+', '_', text).strip('_').lower()
    return name if name else fallback


def generate_test_file(project_dir: str, page_name: str, url: str, elements: list) -> str:
    """
    Generate a pytest test file for the given page and elements.

    Returns the absolute path to the written file.
    """
    tests_dir = os.path.join(project_dir, "tests")
    os.makedirs(tests_dir, exist_ok=True)

    # Create tests/__init__.py if absent
    init_path = os.path.join(tests_dir, "__init__.py")
    if not os.path.exists(init_path):
        open(init_path, 'w').close()

    cls = _class_name(page_name)
    test_cls = f"Test{cls}"

    lines = [
        f'"""',
        f'Tests for {cls}',
        f'Generated by SikuliPy Web Inspector',
        f'URL: {url}',
        f'',
        f'Run with: pytest tests/test_{page_name}.py -v',
        f'"""',
        f'',
        f'import pytest',
        f'from playwright.sync_api import sync_playwright',
        f'from pages.{page_name}_page import {cls}',
        f'',
        f'',
        f'@pytest.fixture(scope="function")',
        f'def page():',
        f'    """Playwright page fixture."""',
        f'    with sync_playwright() as p:',
        f'        browser = p.chromium.launch(headless=True)',
        f'        context = browser.new_context(viewport={{"width": 1920, "height": 1080}})',
        f'        pg = context.new_page()',
        f'        yield pg',
        f'        browser.close()',
        f'',
        f'',
        f'class {test_cls}:',
        f'',
    ]

    # Build method names — must match what pom_generator produced
    name_counts = {}
    methods = []

    for i, el in enumerate(elements):
        display = el['text'] if el['text'] else el.get('ariaLabel', '')
        fallback = f"{el['category'].lower()}_{i}"
        name = _safe_name(display, fallback)

        if name in name_counts:
            name_counts[name] += 1
            name = f"{name}_{name_counts[name]}"
        else:
            name_counts[name] = 0

        methods.append((name, bool(display)))

    for name, has_text in methods:
        # assert_visible test
        lines += [
            f'    def test_{name}_visible(self, page):',
            f'        po = {cls}(page)',
            f'        po.navigate()',
            f'        po.assert_{name}_visible()',
            f'',
        ]
        # assert_text test — only for elements that had text
        if has_text:
            lines += [
                f'    def test_{name}_text(self, page):',
                f'        po = {cls}(page)',
                f'        po.navigate()',
                f'        po.assert_{name}_text()',
                f'',
            ]

    content = '\n'.join(lines)
    out_path = os.path.join(tests_dir, f"test_{page_name}.py")
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return out_path
